export const API_CONFIG = {
  AUTH_SERVICE_URL: import.meta.env.VITE_AUTH_SERVICE_URL,
  OTP_SERVICE_URL: import.meta.env.VITE_OTP_SERVICE_URL,
  PAYMENT_SERVICE_URL: import.meta.env.VITE_PAYMENT_SERVICE_URL,
  NOTIFICATION_SERVICE_URL: import.meta.env.VITE_NOTIFICATION_SERVICE_URL,
  API_KEY: import.meta.env.VITE_API_KEY,
  API_KEY_HEADER: "X-API-Key",
};